data<-read.table("household_power_consumption.txt",header=T,sep=";") 
subData <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
png(filename = "plot1.png",width = 480, height = 480, units = "px", pointsize = 12,bg = "white")
plot1 <- as.numeric(subData$Global_active_power)
hist(plot1, main="Global Active Power", col="red", xlab="Global Active Power (kilowatts)", ylab = "Frequency")
dev.off()
