data<-read.table("household_power_consumption.txt",header=T,sep=";") 
subData <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
plot2 <- as.numeric(subData$Global_active_power)
png(filename = "plot2.png",width = 480, height = 480, units = "px", pointsize = 12,bg = "white")
days <- strptime(paste(subDates$Date, subDates$Time), format="%d/%m/%Y %H:%M:%S")
plot(days, plot2, xlab="", ylab="Global Active Power (kilowatts)", type="l")
dev.off()
